### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#1]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [x] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

Design the home page of the documentation site of Mathball similar to this one:

![](https://drive.google.com/uc?id=13r1rLqPVxF_eHXhb87FtdfQ3ub2Ee0Po)

Instead of *blue*, use this color palette - `#d9703f`

**Comment by sateslayer** [comment]
I am willing to work for this. However I have exams till the end of the next week.

Some clarifications:
What features would you like for the home page?
How do you propose to link the webpage to the Mathball repository?

**Comment by pbiswas101** [comment]
@sateslayer include **Home**, **Docs** & **Contribute** in the navbar and include the Mathball logo with its tagline! 

Give a brief intro on the home page and include a **View on GitHub** snippet at the corner. 
Include a brief footer mentioning copyrights and licenses.

**Comment by pbiswas101** [comment]
By the way, just comment below from when you'll be able to work and I'll assign you. However, if someone else comments before regarding their wish to work on this issue then he/she will be assigned first.

**Comment by sateslayer** [comment]
I will be able to work on this from evening of 8th March(IST) . Sure, in the meanwhile if someone claims the task, let them work on it. Thanks a lot!

**Comment by nilshah98** [comment]
> I will be able to work on this from evening of 8th March(IST) . Sure, in the meanwhile if someone claims the task, let them work on it. Thanks a lot!
> 
> Edit: How do I run this? Because I have only worked with a create-react-app type project till date.

I had a look at the `package.json` and the general file structure. And I think, it follows the `create-react-app` format.
These are the scripts mentioned in the `package.json` file-

``` js
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"
  }
```

So, to run the application - `npm run start` should work.

**Comment by devRD** [comment]
can I work on this issue?

**Comment by pbiswas101** [comment]
@devRD you're assigned!
