### ISSUE TITLE
Modify Features Section (Home Page)

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#12]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [ ] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

Include 4 cards instead of six namely:
- Numbers' Problem
- Helper Functions
- Core Tools
- Data Structures

**Comment by devRD** [comment]
can I work on this?

**Comment by pbiswas101** [comment]
@devRD you're assigned

**Comment by devRD** [comment]
@pbiswas101 Why is the mathball homepage showing up blank?

**Comment by devRD** [comment]
@pbiswas101  Why is the Mathball homepage showing up blank?
