### ISSUE TITLE
Adding Docs Page

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#13]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [x] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

### Layout
![](https://drive.google.com/uc?id=1FzqbfB0RolLRFNAO_8wXzxRNzdaTsVw6)

### Color Palette
`#d9703f`

### Reference
For contents, check out this [link](https://github.com/pbiswas101/Mathball/tree/master/docs).

**Comment by sahilit** [comment]
Can i take this issue

**Comment by pbiswas101** [comment]
@sahilit you're assigned
