### ISSUE TITLE
Resolve Travis CI status

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#15]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [x] Is this a **bug fix**?
- [ ] Is this an **UI/UX improvement**?
- [ ] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

#### Current Status
[![Build Status](https://travis-ci.org/pbiswas101/Mathball-Docs.svg?branch=master)](https://travis-ci.org/pbiswas101/Mathball-Docs)

#### Build Log
![](https://drive.google.com/uc?id=1WI20eSOJIKLMCrVC4fz18CP4WtUpT5LR)

**Comment by sahilit** [comment]
I have resolved this issue while I am working on this #13 Issue.

**Comment by pbiswas101** [comment]
@sahilit okay
