### ISSUE TITLE
Rendering Problem: Home Page

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#17]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [x] Is this a **bug fix**?
- [ ] Is this an **UI/UX improvement**?
- [ ] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

### Current View:
![](https://drive.google.com/uc?id=1yFPtgCqhX3aTymPV603JRMy83nGUEBdu)

### Expected View:
- check this [link](http://illustrious-aftermath.surge.sh/)!

**Comment by sahilit** [comment]
I will be looking into it.

**Comment by pbiswas101** [comment]
@sahilit you're assigned
