### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by nilshah98** [pbiswas101/Mathball-Docs#19]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [x] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

Add documentation for -
- [Modular Inverse](https://github.com/pbiswas101/Mathball-Docs/blob/master/src/components/docContent/ModularInverse.js)
- [Performance](https://github.com/pbiswas101/Mathball-Docs/blob/master/src/components/docContent/Performance.js)
- [Pipe](https://github.com/pbiswas101/Mathball-Docs/blob/master/src/components/docContent/Pipe.js)
- [Priority Queue](https://github.com/pbiswas101/Mathball-Docs/blob/master/src/components/docContent/PriorityQueue.js)

The above 4 components are added to React, but the content inside them is blank, refer other examples to fill them in.

Also, refer their corresponding documentation from [Mathball docs](https://github.com/pbiswas101/Mathball/tree/master/docs).

------------

**Comment by devRD** [comment]
I can work on this.

**Comment by nilshah98** [comment]
Apologies the docs for the same aren't updated on Mathball itself.
