### ISSUE TITLE
Fix Features' Card-Height & Implement Blog Link

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#3]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [x] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

Make the height of the **Feature Cards** same:

![](https://drive.google.com/uc?id=1ZfDdCSf0ybLfsYn7wGJAf70Xyq8AIO3h)

And also provide the **Blog** Link on the NavBar to this article - [https://medium.freecodecamp.org/how-to-get-started-with-competitive-programming-in-javascript-76ad2e760efe](https://medium.freecodecamp.org/how-to-get-started-with-competitive-programming-in-javascript-76ad2e760efe)

![](https://drive.google.com/uc?id=12Bnj3l8A4QYX-WI2zfDAMjuQwL090RAO)

**Comment by German-Corpaz** [comment]
Can i grab this?

**Comment by pbiswas101** [comment]
@German-Corpaz this issue is only for `gssoc19` participants! You can raise new ones by yourself and you'll be assigned to them.

**Comment by punkstar25** [comment]
can i work on it...

**Comment by pbiswas101** [comment]
@punkstar25 what is your gssoc19 slack username?

**Comment by punkstar25** [comment]
sry but i am newbie in open source and i don't have any slack user name. is it necessary to have account on slack to work on this issue...

**Comment by Manvityagi** [comment]
@pbiswas101 May I work on this ?

**Comment by pbiswas101** [comment]
@punkstar25 this issue is only for `gssoc19` participants

**Comment by punkstar25** [comment]
can i participate in gssoc19...

**Comment by pbiswas101** [comment]
@punkstar25 actually it already started from 1st March!

**Comment by punkstar25** [comment]
ok,thanks for the guidance

**Comment by Manvityagi** [comment]
@pbiswas101 May I work on this ?

**Comment by pbiswas101** [comment]
@Manvityagi you're assigned!
