### ISSUE TITLE
Align the footer content in the center

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#4]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [x] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

Align the **footer** content in the middle:

![](https://drive.google.com/uc?id=14TST4KPr0DrtG19IUE1hO5o4td7LTvQs)

**Comment by viditkumar** [comment]
Could you please assign this issue to me?

**Comment by pbiswas101** [comment]
@viditkumar this issue is only for `gssoc19` participants.

**Comment by Manvityagi** [comment]
Can I work on this ?

**Comment by Manvityagi** [comment]
@pbiswas May I work on this ??

**Comment by pbiswas101** [comment]
@Manvityagi you're assigned
