### ISSUE TITLE
Provide Version Numer

### ISSUE THREAD

**Issue by pbiswas101** [pbiswas101/Mathball-Docs#5]
### Do the checklist before filing the issue:

- [x] Do you have npm and all the relevant dependencies installed?
- [ ] Is this a **bug fix**?
- [x] Is this an **UI/UX improvement**?
- [x] Is this a **feature request**?

###### NOTE: Provide a clear and concise description of the feature that needs to be added! Or if its a bug, then provide the necessary steps to reproduce it along with screenshots.

- *Give your answer below:*

------------

In the navbar, provide the number `v0.2.0` in place of **Version**:

![](https://drive.google.com/uc?id=1kgGoqGKDmEM0LlFY60A3Y4Vzdat3_QyQ)

Also, make a slight change on the tagline **A JavaScript Library for competitive programming.** with the following text:

```
A JavaScript library for Competitive Programming
```

**Comment by sateslayer** [comment]
I'll do it.

**Comment by pbiswas101** [comment]
@sateslayer First complete your current PR!

**Comment by sateslayer** [comment]
I asked a doubt over there. Unless that is fixed I can't move forward!

**Comment by viditkumar** [comment]
Please assign this to me.

**Comment by Manvityagi** [comment]
can I take this? @pbiswas101

**Comment by pbiswas101** [comment]
@Manvityagi you're assigned!
